Update edgecmd-commands.md
osisoft/Edgecmd-Docs pull request #17
Opened 2021-01-08 11:19 UTC by TinaUll

Hi, I've added the data discovery config to the edgecmd reference. Please let me know if anything is missing or incorrect. Thank you!

2021-01-12 21:44 UTC, zryska commented on V1.2/Reference/edgecmd-commands.md
> +| `edgecmd add discoveries -cid <componentId> -query "<queryFilter>" -id <discoveryId>` | Search all items that have the query filter string in specified discovery of specified component | `edgecmd a
This starts a new discovery operation with query "+/+/Device90" and Id "1"

2021-01-12 21:45 UTC, zryska commented on V1.2/Reference/edgecmd-commands.md
> +`edgecmd add discoveries -cid <componentId>` | Add data source discoveries to specified component | `edgecmd add discoveries -cid Mqtt1`|
This starts a new discovery operation and returns status object containing generated Id of the discovery

2021-01-12 21:46 UTC, zryska commented on V1.2/Reference/edgecmd-commands.md
> +`edgecmd get discoveries -cid <componentId>` | Get active data source discoveries for specified component | `edgecmd get discoveries -cid Mqtt1`|
This present you with ative as well as completed discovery status information. (array of discovery operation statuses)

2021-01-12 21:47 UTC, zryska commented on V1.2/Reference/edgecmd-commands.md
> +| `edgecmd get discoveries -cid <componentId> -id <discoveryId> -result -query diff=<discoveryId> [-csv]` | Search the differences between two specified discoveries of specified component | `edgecmd
Would be Get differences better?

2021-01-12 21:48 UTC, zryska commented on V1.2/Reference/edgecmd-commands.md
> +| `edgecmd add dataselection -cid <componentId> -select -query discoveryId=<discoveryId>` | Add specified discovery to data selection and select automatically | `edgecmd add dataselection -cid Mqtt1
Add specified discovery result to data selection and set all the items to selected - or something along those lines?

2021-01-12 21:52 UTC, zryska commented on V1.2/Reference/edgecmd-commands.md
> +| `edgecmd get dataselection -cid <componentId> [-csv]` | Get discoveries added to data selection | `edgecmd get dataselection -cid Mqtt1` |
This is part of dataselection - not really related to discovery but maybe it's useful to have it here

2021-01-12 21:52 UTC, zryska commented on V1.2/Reference/edgecmd-commands.md
> +| `edgecmd get dataselection -cid <componentId> -query diff=<discoveryId> [-csv]` | Compare data selection against a discovery | `edgecmd get dataselection -cid Mqtt1 -query diff=2` |
against a discovery result

2021-01-12 21:53 UTC, zryska commented on V1.2/Reference/edgecmd-commands.md
> +| `edgecmd  remove discoveries -cid <componentId> -id <discoveryId> [-y]` | Remove the specified discovery from the specified component | `edgecmd  remove discoveries -cid Mqtt1 -id 2 -y`|
Remove all discovery states as well as results.

2021-01-12 21:55 UTC, zryska commented on V1.2/Reference/edgecmd-commands.md
> +| `edgecmd  remove discoveries -cid <componentId> -id <discoveryId> -result [-y]` | Remove only the result of the specified discovery from the specified component | `edgecmd  remove discoveries -cid
It also cancels the discovery if it's still running.

2021-01-12 21:56 UTC, zryska requested changes
Some of the sentenses could be rephrased a bit - please see my comments. Thank you!

2021-01-15 21:42 UTC, merged

2021-01-15 22:31 UTC, rgralakosi reviewed
The changes look good!